<p><?=$this->translate("Welcome");?>, <?php echo Zend_Auth::getInstance()->getIdentity()->user_name ?>.<br>
<?=$this->translate("Ussing role");?>: <?php echo $this->list['role']; ?>.<br>
<?=$this->translate("Available resources");?>:
<?php 
	$a=0;
	foreach ($this->list['allowed'] as $resource => $access) :?> 
<div><?=$a;?> User: 
	<?php 
		$a++;
		if (is_object(Zend_Auth::getInstance()->getIdentity())) 
			echo Zend_Auth::getInstance()->getIdentity()->user_name; 
		else echo "Unknown";?>  
	is <?=$access=='allowed'?'<font color="green">allowed</font>':'<font color="red">denied</font>' ?> <?=$this->translate("access to");?> <?php echo $resource ?>
</div> 
<?php endforeach; ?>