<!--[if !IE]>start section<![endif]-->
<div class="section">
	

				<h2><?=$this->translate("Resource list");?>:</h2>
			

			<div class="table_tabs_menu">
			
			<a class="update" href="<?php echo $this->url(array('controller'=>'resources','action'=>'add'));?>">
				<span><span><em><?=$this->translate("Add New Resource");?></em><strong></strong></span></span>
			</a>
			
			</div>
		
			
				<table cellpadding="0" cellspacing="0" width="100%">
					
					<tbody><tr>
						<th><?=$this->translate("Module");?></th>
				        <th><?=$this->translate("Resource");?></th>
				        <th><?=$this->translate("Name");?></th>																
						<th style="width: 165px;">Actions</th>
					</tr>	
					<?php foreach($this->paginator as $entry) : ?>
						<tr class="<?php echo $this->cycle(array("first","second"))->next()?>" >
							<td><?php echo $this->escape($entry['module_name']);?></td>
				            <td><?php echo $this->escape($entry['resource']);?></td>
				            <td><?php echo $this->escape($entry['name_r']);?></td>								            
				            <td>
								<div class="actions_menu">
									<ul>
										<li><a class="edit" href="<?php echo $this->url(array('controller'=>'resources','action'=>'edit', 'uid'=>$entry['uid']));?>"><?=$this->translate("Edit");?></a></li>
										<li><a class="delete" href="<?php echo $this->url(array('controller'=>'resources','action'=>'delete', 'uid'=>$entry['uid']));?>"><?=$this->translate("Delete");?></a></li>
									</ul>
								</div>
							</td>
						</tr>
					<?php endforeach; ?>									
				</tbody></table>
				
		<?php echo $this->paginator; ?>						
