<!--[if !IE]>start section<![endif]-->
<div class="section">
	
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<span class="title_wrapper_top"></span>
		<div class="title_wrapper_inner">
			<span class="title_wrapper_middle"></span>
			<div class="title_wrapper_content">
				<h2><?=$this->translate("Resources by role list");?>:</h2>
			</div>
		</div>
		<span class="title_wrapper_bottom"></span>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<span class="section_content_top"></span>
		
		<div class="section_content_inner">				
		
			<!--[if !IE]>start table_wrapper<![endif]-->
			<div class="table_wrapper">
				<div class="table_wrapper_inner">
					<p><?= $this->form ?><br>
					<?=$this->translate("Available resources");?>:
					</p>					
				<table cellpadding="0" cellspacing="0" width="100%">					
					<tbody><tr>
						<th style="width: 147px;"><?=$this->translate("Number");?></th>
						<th style="width: 147px;"><?=$this->translate("Role");?></th>
						<th class="photo"><span><?=$this->translate("Access");?></span></th>
						<th><a href="#" class="asc"><?=$this->translate("Resource");?></a></th>						
					</tr>						
					<?php $a=0;foreach($this->list['allowed'] as $resource => $access) : ?>
						<tr class="<?php $a++;echo $this->cycle(array("first","second"))->next()?>" >
							<td><?=$a;?></td>
							<td><?php echo $this->escape($this->list['role']);?></td>
				            <td><?=$access=='allowed'?'<font color="green">allowed</font>':'<font color="red">denied</font>' ?></td>
				            <td><?php echo $resource ?></td>
				            
						</tr>
					<?php endforeach; ?>									
				</tbody></table>
				</div>
			</div>
			<!--[if !IE]>end table_wrapper<![endif]-->
			
		</div>
		<?php echo $this->paginator; ?>						
		<span class="section_content_bottom"></span>
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->