<?php 
/*
<div class="article">
	<h1>
		<a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>" class="work_date"><?php echo $this->escape($this->title) ?></a>
	</h1>
	<a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>"></a>
	<?php echo $this->body ?>
	<?php if(!empty($this->has_extended)): ?>
	    <p><a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>#extended">Continue reading <?php echo $this->escape($this->title) ?></a></p>
	<?php endif; ?>
	<p class="date"><?php echo $this->escape($this->formatDbDate($this->date)) ?></p>
	<p class="post_details">
		<a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>" class="permalink">Article</a>
		posted by 
		<a href="#"><?=$this->escape($this->author);?></a> 		
		&nbsp;&nbsp;&nbsp;
		<a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>#comments">
			<strong>Comments (<?php echo $this->escape($this->comment_count) ?>)</strong>
		</a>
	</p>
</div>
<hr/>
*/
?>
<div class="news_title">
	<h3 class="bg">
		<a href="blog<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>">
			<?php echo $this->escape($this->title) ?>
		</a>
	</h3>
	<span><?php echo $this->escape($this->formatDbDate($this->date, 'dd.MM.YY')) ?></span> <br style="clear: both;"/>
</div>
<p><?=substr($this->body,0,80);?>...</p>