
<div class="post">
	<h2 class="title"><a href="#"><?=$this->entry['tittle'];?> </a></h2>
	<p class="meta">Posted by <a href="#"><?=$this->entry['user'];?></a> on <?=$this->entry['date'];?>
		& <a href="#" class="permalink">Full article</a></p>
	<div class="entry">
		<p><img src="/assets/images/<?=$this->entry['image'];?>" alt="" width="143" height="143" class="alignleft" />
			<?=$this->entry['content'];?></p>
		<p class="clearfix">&nbsp;</p>
	</div>
</div>

