<form action="<?= $this->url(
			array('module' => 'users',
				  'controller' => 'modules',
				  'action'=>'delete'), 'default', true) ?>" method="post">
<h3>
	<?=$this->translate("Are you sure you want to delete");?> 
	'<?php echo $this->escape($this->entry['module_name']); ?>'?
</h3><br/>
<!--[if !IE]>start forms<![endif]-->
<input type="hidden" name="module_id" value="<?php echo $this->entry['module_id']; ?>" />


<input type="submit" name="del" value="<?=$this->translate("Yes");?>" /></span>
<input type="submit" name="del" value="<?=$this->translate("No");?>" /></span> 
</form>				